Flask_Restful/blueprints/courses.py
from flask import Blueprint, request, render_template
from flask import jsonify

courses_list = [
    {'id': 1, 'name': 'ECO311'},
    {'id': 2, 'name': 'ECO400'},
    {'id': 3, 'name': 'INF310'}
]

courses_blueprint = Blueprint('courses_blueprint', __name__, template_folder='templates')
  
@courses_blueprint.route('/<int:course_id>/<name>', methods=['PUT', 'POST'])  
def c_put_post(course_id,name): 
    if request.method == 'POST':
        id_exist = False
        for m in range(len(courses_list)):
            if courses_list['id'][m-1] == course_id:
                course_id = True

        if id_exist == False:
                courses_list.append(dict({'id': course_id, 'name': name}))
                return jsonify(courses_list)
        return jsonify(courses_list)
        
    if request.method == 'PUT':
        for n in courses_list:
            if n['id'] == event_id:
                n.update({'name': name})
                return jsonify(n)

        events_list.append(dict({'id:': course_id, 'name': name}))
        return jsonify(courses_list)


@courses_blueprint.route('/<int:course_id>', methods=['GET', 'DELETE'])

def c_get_delete(course_id): 
    if request.method == 'GET':
        flag = False
        for courses in courses_list:
            if courses['id'] == course_id:
                flag = True
                return jsonify(courses)
        if flag == False:    
            return 'Not able to find ID!'
    
    if request.method == 'DELETE':
        flag = False
        for a in range(len(courses_list)): 
            if courses_list[a]['id'] == course_id: 
                del courses_list[a]
                flag = True
                return 'Course deleted successfully!'

        if flag == False:
            return 'Not able to find ID!'

@courses_blueprint.route('/all', methods=['GET'])
def get_all():
    return render_template('courses.html', course=courses_list)

Flask_Restful/blueprints/events.py
from flask import Blueprint, request, render_template
from flask import jsonify

events_list = [
    {'id': 1, 'name_event': 'Spring Fest'},
    {'id': 2, 'name_event': 'Colors Festivals'},
    {'id': 3, 'name_event': 'Carnivals'}
]

events_blueprint = Blueprint('events_blueprint', __name__, template_folder='templates')

@events_blueprint.route('/<int:event_id>/<name>', methods=['PUT', 'POST'])
    
def put_post(event_id,name):
    if request.method == 'POST':
        id_exist = False
        for m in range(len(events_list)):
            if events_list['id'][m-1] == event_id:
                id_exist = True
                    
        if id_exist == False:
            events_list.append(dict({'id': event_id, 'name_event': name_event}))
            return jsonify(events_list)
        return jsonify(events_list)

    if request.method == 'PUT':
            for n in events_list:
                if n['id'] == event_id:
                    n.update({'name_event': name_event})
                    return jsonify(n)

            events_list.append(dict({'id:': event_id, 'name_event': name_event}))
            return jsonify(events_list)

@events_blueprint.route('/<int:event_id>', methods=['GET', 'DELETE'])
def get_delete(event_id): 
    if request.method == 'GET':
        flag = False
        for event in events_list:
            if event['id'] == event_id:
                flag = True
                return jsonify(event)
        if flag == False:    
            return 'ID not Found!'

    if request.method == 'DELETE':
        flag = False
        for a in range(len(events_list)): 
            if events_list[a]['id'] == event_id: 
                del events_list[a]
                flag = True
                return 'Event deleted successfully!'

        if flag == False:
            return 'Not able to find ID!'

@events_blueprint.route('/all', methods=['GET'])
def get_all():
    return render_template('events.html', events=events_list)

Flask_Restful/blueprints/students.py
from flask import Blueprint, request, render_template
from flask import jsonify

students_list = [
    {'id': 1, 'student': 'Lil Fame'},
    {'id': 2, 'student': 'Jacopo Sala'},
    {'id': 3, 'student': 'Ilda Duke'}
]

students_blueprint = Blueprint('students_blueprint', __name__, template_folder='templates') 

@students_blueprint.route('/<int:student_id>/<name>', methods=['PUT', 'POST'])
def s_put_post(student_id,name):   
    if request.method == 'POST':
        id_exist = False
        for m in range(len(students_list)):
            if students_list['id'][m-1] == student_id:
                id_exist=True

        if id_exist ==  False:
            students_list.append(dict({'id': student_id, 'name': name}))
            return jsonify(students_list)
        return jsonify(students_list)

    if request.method == 'DELETE':
        for n in students_list:
            n.update({'name': name})
            return jsonify(n)
    
        students_list.append(dict({'id': student_id, 'name': name}))
        return jsonify(students_list)

@students_blueprint.route('/<int:student_id>', method=['GET', 'DELETE'])
def s_delete_get(student_id):  
    if request.method == 'GET':
        flag = False
        for student in students_list:
            if student['id'] == student_id:
                flag = True
                return jsonify(student)
        if flag == False:    
            return 'Not able to find ID!'
       
    else: 
        flag = False
        for i in range(len(students_list)): 
            if students_list[i]['id'] == student_id: 
                del students_list[i]
                flag = True
                return 'Student deleted successfully!'

        if flag == False:
            return 'Not able to find ID!'

@students_blueprint.route('/all', methods=['GET'])
def get_all():
    return render_template('students.html', students=students_list)
    

Flask_Restful/flask_blueprint.py
from flask import Flask, jsonify, render_template
from blueprints.students import students_blueprint
from blueprints.courses import courses_blueprint
from blueprints.events import events_blueprint


app = Flask(__name__)

@app.route('/')
def home():
    return render_template("index.html")

    
app.register_blueprint(students_blueprint, url_prefix='/v1/student')

app.register_blueprint(events_blueprint, url_prefix='/v2/event')

app.register_blueprint(courses_blueprint, url_prefix='/v3/course')

Flask_Restful/templates/courses.html
{% extends 'index.html' %}
{% block title %} Courses {% endblock title %}
{% block content %}
    <table>
        <tbody>
            {% for course in courses %}
                {% for key, value in courses.items() %}
                <h2>Key: {{key}}</h2>
                <h2>Value: {{value}}</h2>
                {% endfor %}
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

Flask_Restful/templates/events.html
{% extends "index.html" %}
{% block title %} Events {% endblock %}
{% block content %}
    <table>
        <tbody>
            {% for event in events %}
                {% for key, value in event.items() %}
                <h1>Key: {{key}}</h1>
                <h1>Value: {{value}}</h1>
                {% endfor %}
            {% endfor %}
        </tbody>
    </table>

{% endblock %}

Flask_Restful/templates/index.html
<!DOCTYPE html>
<html>
<body>

        <a href="{{url_for('courses_blueprint.get_all')}}">List of all courses</a> 
        <a href="{{url_for('students_blueprint.get_all')}}">List of all students</a> 
        <a href="{{url_for('events_blueprint.get_all')}}">List of all events</a> 

        {% block body %}{% endblock %}


</body>
</html> 

Flask_Restful/templates/students.html
{% extends 'index.html' %}
{% block title %}Students {% endblock title %}
{% block main %}
    <table>
        <tbody>
            {% for student in students %}
                {% for key, value in students.items() %}
                <h2>Key: {{key}}</h2>
                <h2>Value: {{value}}</h2>
                {% endfor %}
            {% endfor %}
        </tbody>
    </table>
{% endblock %}